### ISSUE TITLE
Class is not defined

### ISSUE THREAD

**Issue by juanbrujo** [seykron/junar-javascript-sdk#1]
Tengo este error siempre ( node -v **v0.10.33** y usando require() ):

```
ERROR Unable to load /Library/WebServer/Documents/pudu-bot/scripts/quake: ReferenceError: Class is not defined
  at Object.<anonymous> (/Library/WebServer/Documents/pudu-bot/node_modules/junar/lib/junar.js:6:30)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Library/WebServer/Documents/pudu-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Library/WebServer/Documents/pudu-bot/node_modules/junar/index.js:1:80)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Library/WebServer/Documents/pudu-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Library/WebServer/Documents/pudu-bot/scripts/quake.js:17:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Library/WebServer/Documents/pudu-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Robot.loadFile (/Library/WebServer/Documents/pudu-bot/node_modules/hubot/src/robot.coffee:217:9, <js>:164:20)
  at Robot.load (/Library/WebServer/Documents/pudu-bot/node_modules/hubot/src/robot.coffee:239:9, <js>:187:30)
  at Shell.loadScripts (/Library/WebServer/Documents/pudu-bot/node_modules/hubot/bin/hubot:93:5, <js>:94:13)
  at Shell.emit (events.js:92:17)
  at /Library/WebServer/Documents/pudu-bot/node_modules/hubot/src/adapters/shell.coffee:35:7, <js>:72:22
  at Interface.<anonymous> (/Library/WebServer/Documents/pudu-bot/node_modules/hubot/src/adapters/shell.coffee:96:11, <js>:157:20)
  at Interface.emit (events.js:117:20)
  at Interface.close (readline.js:272:8)
  at ReadStream.onend (readline.js:95:10)
  at ReadStream.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
```

**Comment by ghost** [comment]
Hola, alguna idea de cómo resolver esto? Da la impresión de que el ejemplo estuviera desactulizado, u omitiendo alguna librería necesaria.

**Comment by seykron** [comment]
El proyecto usa prototype como librería para construir clases prototipales, y no se estaba incluyendo correctamente. No entiendo cómo estaba funcionando antes...

No sé si el API de Junar sigue siendo el mismo que hace cuatro años cuando subí este proyecto. Por el momento no le estoy dando más soporte, si alguna persona quiere tomar el ownership del proyecto es bienvenida.

Ya publiqué la versión 0.0.3 con este fix, si hacen un `npm update` debería funcionar (si el API de Junar no cambió)

**Comment by juanbrujo** [comment]
@seykron sabes cual es entonces el metodo oficial para trabajar con datos de datos.gob.cl?

**Comment by seykron** [comment]
@juanbrujo No sé si te sirve, pero [en esta wiki está la documentación de la API](http://es.wiki.junar.com/index.php/Recursos_datos_gob_cl_API) a la que hace referencia el [sitio para desarrolladores](http://recursos.datos.gob.cl/developers/) de datos.gob.cl.

Aparentemente, este proyecto (junar-javascript-sdk) sigue estando como referencia, así que es posible que siga funcionando con la API de Junar. En teoría, el ejemplo de la homepage debería funcionar:

```
var junar = require("junar").create({
  authKey : "[your-junar-api-key]"
});
junar.stream("LATES-7-AROUN-THE-WORLD", [], function(response) {
  var table = response.result;
  var region = table.result.getValue(2, 7).getValue();
  var magnitude = table.getValue(2, 2);

  console.log("Last earthquake ocurred in " + region +
    " with a magnitude of " + magnitude);
});

```

**Comment by juanbrujo** [comment]
gracias, probe ese mismo ejemplo y no devuelve nada, por eso preguntaba.
